/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type PersonId = number;
export type SkillId = number;
export type Level = string;

export interface PersonSkill {
  id: Id;
  personId?: PersonId;
  skillId?: SkillId;
  level: Level;
}
